### PR TITLE
feat: MergeSort

### PR DESCRIPTION
**Pull request by EvolveArt**
- Implement MergeSort sorting algorithm
- Create a new `sorting` module 
- Unit tests for MergeSort
- Add `split` and `fill` array utils methods

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #23 

## What is the new behavior?

N/A

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by EvolveArt** [comment]
Still wip. Need to add more tests and fix small issues. Working with `Array` is still hard with current cairo version. Would be great to be able to initialize an array easily instead of having to do sequential `append` calls.

**Comment by abdelhamidbakhta** [comment]
> Still wip. Need to add more tests and fix small issues. Working with `Array` is still hard with current cairo version. Would be great to be able to initialize an array easily instead of having to do sequential `append` calls.

can you addd this to the wish list ?

**Comment by EvolveArt** [comment]
Should be good to merge!

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Pull request merged**
