### PR TITLE
array ext with span 

### PR DESCRIPTION
**Pull request by gaetbout**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

This PR should solve https://github.com/keep-starknet-strange/quaireaux/issues/75.  
I also fixed the previous interface and now all fn should use @ Array instead of Array.

I also took some time to update `x = x + 1` to `x += 1`

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

Some fn where update to return an Option instead of panicking. 

This PR took me a about 3 hours

### CODE REVIEW

**Comment by gaetbout** [comment]
@abdelhamidbakhta

**Comment by enitrat** [comment]
can you add this, this saves me a PR

```rust
    /// Removes the first `n` elements from the Span.
    fn pop_front_n(ref self: Span<T>, mut n: usize) {
        loop {
            if n == 0 {
                break ();
            }
            self.pop_front();
            n = n - 1;
        };
    }
```

**Comment by gaetbout** [comment]
The CI job failed due to github error, it should be fine.

**Comment by gaetbout** [comment]
Green for merge, @enitrat changes integrated.
CI still red, I'm quite confused...

**Comment by enitrat** [comment]
rc0 and main have different formatters. that could cause an issue with CI.

**Comment by gaetbout** [comment]
Weird that it worked on Main then

**Comment by gaetbout** [comment]
Also did `pop_back_n` but that one can only be performed on Span

**Pull request merged**
